### ISSUE TITLE
txt文件获取

### ISSUE THREAD

**Issue by xianfangfx** [Zzh-tju/DIoU#4]
您好，请问，test_1715k.m中iou-1715k.txt、giou-1715k.txt、diou-1715k.txt、ciou-1715k.txt如何获取？这是公开数据集吗？

**Comment by Zzh-tju** [comment]
不是，这是运行test_1715k.m后自动生成的txt文件，用于保存结果。

**Comment by xianfangfx** [comment]
> 不是，这是运行test_1715k.m后自动生成的txt文件，用于保存结果。

谢谢

**Comment by xianfangfx** [comment]
请问，运行需要大概多久的时间？我预算可能一周以上？如果是这样，您方便将您生成的结果（txt文档）发给我吗？谢谢

**Comment by Zzh-tju** [comment]
此实验不是使用GPU工作站，而在另一台设备上跑。由于疫情缘故，没有返校，故而目前无法提供txt。1715k一次三四天。你可以适当调小，比如圆内撒点数量减半，或者长宽比和面积从7种减为5种，都可以大大缩短时间。

**Comment by xianfangfx** [comment]
您好，请问您的DIoU-SSD-pytorch-master文件，可以在CPU环境下运行吗？如果可以，需要修改哪些地方，谢谢。

**Comment by Zzh-tju** [comment]
应该是不行，怎么改就超出了我的知识上限了o(╥﹏╥)o
