### ISSUE TITLE
求助：请问为什么用darknet yolov3训练时，log日志中显示的还是giou，而且训练loss比用giou的高，请问这是啥原因呢，谢谢！

### ISSUE THREAD

**Issue by 1343464520** [Zzh-tju/DIoU#5]
![train_log_part](https://user-images.githubusercontent.com/24668916/81395364-13957b80-9156-11ea-8c6b-c37da17f0bd6.png)

**Comment by 1343464520** [comment]
我在检测的那三层后面加了：
iou_normalizer=0.5
cls_normalizer=1.0
iou_loss=ciou
nms_kind=greedynms
beta1=0.6

**Comment by 1343464520** [comment]
我的cfg文件如下：
[net]
# Testing
#batch=1
#subdivisions=1
# Training
# batch=64
# subdivisions=16
batch=32
subdivisions=16

width=416
height=416

#width=512
#height=512
channels=3
momentum=0.9
decay=0.0005
angle=5
saturation = 1.5
exposure = 1.5
hue=.1

### ddj add...
#mixup=1
#cutmix=1
#mosaic=1
#blur=1
################

#learning_rate=0.001
learning_rate=0.01
burn_in=1000
max_batches = 50000
policy=steps
steps=200,800,2000,4000,8000,15000,30000
#steps=15000,16000
scales=.5,.5,.5,.5,.5,.5,.5

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

# Downsample

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=128
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=256
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=512
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

######################

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 6,7,8
anchors = 17,21,  40,21,  68,22,  94,23,  109,21,  122,23,  126,27,  160,22,  207,22  # sill new data 416x416 ubuntu shuffle 
classes=1
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
# add giou loss
#iou_normalizer=0.25
#cls_normalizer=1.0
#iou_loss=giou
# add ciou loss
iou_normalizer=0.5
cls_normalizer=1.0
iou_loss=ciou
nms_kind=greedynms
beta1=0.6

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 61



[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 3,4,5
anchors = 17,21,  40,21,  68,22,  94,23,  109,21,  122,23,  126,27,  160,22,  207,22  # sill new data 416x416 ubuntu shuffle 
classes=1
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
# add giou loss
#iou_normalizer=0.25
#cls_normalizer=1.0
#iou_loss=giou
# add ciou loss
iou_normalizer=0.5
cls_normalizer=1.0
iou_loss=ciou
nms_kind=greedynms
beta1=0.6

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 36



[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 0,1,2
anchors = 17,21,  40,21,  68,22,  94,23,  109,21,  122,23,  126,27,  160,22,  207,22  # sill new data 416x416 ubuntu shuffle 
 
classes=1
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
# add giou loss
#iou_normalizer=0.25
#cls_normalizer=1.0
#iou_loss=giou
# add ciou loss
iou_normalizer=0.5
cls_normalizer=1.0
iou_loss=ciou
nms_kind=greedynms
beta1=0.6

**Comment by 1343464520** [comment]
上面大号粗黑体在cfg中都是注释掉的，显示的问题。。。

**Comment by Zzh-tju** [comment]
显然这不是使用我的repo的训练输出。
如果是https://github.com/Zzh-tju/DIoU-darknet
就没有问题。我刚刚测试了
`
./darknet detector train cfg/voc-ciou.data cfg/voc-ciou.cfg darknet53.conv.74 --gpus 0,1
`
```
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.160846, CIOU: 0.109033), Class: 0.455774, Obj: 0.497935, No Obj: 0.459067, .5R: 0.000000, .75R: 0.000000, count: 5
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.064099, CIOU: -0.048820), Class: 0.769042, Obj: 0.302707, No Obj: 0.513355, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.466621, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1137.725464
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.232801, CIOU: 0.211622), Class: 0.383240, Obj: 0.503172, No Obj: 0.462374, .5R: 0.000000, .75R: 0.000000, count: 2
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.215681, CIOU: 0.215456), Class: 0.342119, Obj: 0.121874, No Obj: 0.513232, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.469092, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1136.798950
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.210665, CIOU: 0.163074), Class: 0.469379, Obj: 0.561193, No Obj: 0.460269, .5R: 0.250000, .75R: 0.000000, count: 4
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.293309, CIOU: 0.263840), Class: 0.539059, Obj: 0.475476, No Obj: 0.512379, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: 0.551950, CIOU: 0.547578), Class: 0.125250, Obj: 0.204644, No Obj: 0.467130, .5R: 1.000000, .75R: 0.000000, count: 1
train_network_err: 1135.440063
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.119378, CIOU: 0.117855), Class: 0.689940, Obj: 0.460485, No Obj: 0.460324, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.275015, CIOU: 0.246272), Class: 0.296907, Obj: 0.615617, No Obj: 0.513529, .5R: 0.000000, .75R: 0.000000, count: 3
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.466939, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1132.094727
train_network sum: 4542.059082 / 8
7: 567.757385, 567.498413 avg, 0.000000 rate, 0.456348 seconds, 56 images
Loaded: 0.000046 seconds
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.211749, CIOU: 0.202135), Class: 0.658431, Obj: 0.322365, No Obj: 0.462490, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.262051, CIOU: 0.254771), Class: 0.426819, Obj: 0.782858, No Obj: 0.512206, .5R: 0.000000, .75R: 0.000000, count: 1
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.468074, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1128.728638
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.551529, CIOU: 0.526662), Class: 0.486327, Obj: 0.482804, No Obj: 0.460465, .5R: 0.500000, .75R: 0.500000, count: 2
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.512807, .5R: -nan, .75R: -nan, count: 0
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.468829, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1132.304077
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.122917, CIOU: -0.044101), Class: 0.570439, Obj: 0.484558, No Obj: 0.461125, .5R: 0.000000, .75R: 0.000000, count: 2
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.240738, CIOU: 0.204894), Class: 0.437907, Obj: 0.354213, No Obj: 0.513501, .5R: 0.000000, .75R: 0.000000, count: 3
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.467784, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1133.650391
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.255730, CIOU: 0.245869), Class: 0.405298, Obj: 0.524315, No Obj: 0.462522, .5R: 0.000000, .75R: 0.000000, count: 2
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.513409, .5R: -nan, .75R: -nan, count: 0
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.469859, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1134.588501
train_network sum: 4529.271484 / 8
8: 566.158936, 567.364441 avg, 0.000000 rate, 0.410363 seconds, 64 images
Loaded: 0.000040 seconds
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.062998, CIOU: -0.028079), Class: 0.722950, Obj: 0.497665, No Obj: 0.463482, .5R: 0.000000, .75R: 0.000000, count: 4
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.511521, .5R: -nan, .75R: -nan, count: 0
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.467789, .5R: -nan, .75R: -nan, count: 0
train_network_err: 1128.023071
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.158216, CIOU: 0.137621), Class: 0.589739, Obj: 0.456860, No Obj: 0.465134, .5R: 0.000000, .75R: 0.000000, count: 3
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.142218, CIOU: 0.011128), Class: 0.462262, Obj: 0.684095, No Obj: 0.513644, .5R: 0.000000, .75R: 0.000000, count: 2
v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: 0.190844, CIOU: 0.169876), Class: 0.442428, Obj: 0.458559, No Obj: 0.469251, .5R: 0.000000, .75R: 0.000000, count: 1
train_network_err: 1140.072632
```

**Comment by 1343464520** [comment]
谢谢大佬回复！是的，你的repo我简单改了下makefile文件在ubuntu上编译出了一些问题，我就改了下前面跟显卡型号相关的几行，没有深入去看，后面我了解yolov4作者用过你的loss，所以我直接在他的repo下跑的😂😂------------------ 原始邮件 ------------------
发件人: "Zzh-tju"<notifications@github.com>
发送时间: 2020年5月8日(星期五) 晚上6:30
收件人: "Zzh-tju/DIoU"<DIoU@noreply.github.com>;
抄送: "1343464520"<1343464520@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Zzh-tju/DIoU] 求助：请问为什么用darknet yolov3训练时，log日志中显示的还是giou，而且训练loss比用giou的高，请问这是啥原因呢，谢谢！ (#5)




 
显然这不是使用我的repo的训练输出。
 如果是https://github.com/Zzh-tju/DIoU-darknet
 就没有问题。我刚刚测试了
 ./darknet detector train cfg/voc-ciou.data cfg/voc-ciou.cfg darknet53.conv.74 --gpus 0,1
 `
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.160846, CIOU: 0.109033), Class: 0.455774, Obj: 0.497935, No Obj: 0.459067, .5R: 0.000000, .75R: 0.000000, count: 5
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.064099, CIOU: -0.048820), Class: 0.769042, Obj: 0.302707, No Obj: 0.513355, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.466621, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1137.725464
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.232801, CIOU: 0.211622), Class: 0.383240, Obj: 0.503172, No Obj: 0.462374, .5R: 0.000000, .75R: 0.000000, count: 2
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.215681, CIOU: 0.215456), Class: 0.342119, Obj: 0.121874, No Obj: 0.513232, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.469092, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1136.798950
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.210665, CIOU: 0.163074), Class: 0.469379, Obj: 0.561193, No Obj: 0.460269, .5R: 0.250000, .75R: 0.000000, count: 4
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.293309, CIOU: 0.263840), Class: 0.539059, Obj: 0.475476, No Obj: 0.512379, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: 0.551950, CIOU: 0.547578), Class: 0.125250, Obj: 0.204644, No Obj: 0.467130, .5R: 1.000000, .75R: 0.000000, count: 1
 train_network_err: 1135.440063
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.119378, CIOU: 0.117855), Class: 0.689940, Obj: 0.460485, No Obj: 0.460324, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.275015, CIOU: 0.246272), Class: 0.296907, Obj: 0.615617, No Obj: 0.513529, .5R: 0.000000, .75R: 0.000000, count: 3
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.466939, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1132.094727
 train_network sum: 4542.059082 / 8
 7: 567.757385, 567.498413 avg, 0.000000 rate, 0.456348 seconds, 56 images
 Loaded: 0.000046 seconds
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.211749, CIOU: 0.202135), Class: 0.658431, Obj: 0.322365, No Obj: 0.462490, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.262051, CIOU: 0.254771), Class: 0.426819, Obj: 0.782858, No Obj: 0.512206, .5R: 0.000000, .75R: 0.000000, count: 1
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.468074, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1128.728638
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.551529, CIOU: 0.526662), Class: 0.486327, Obj: 0.482804, No Obj: 0.460465, .5R: 0.500000, .75R: 0.500000, count: 2
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.512807, .5R: -nan, .75R: -nan, count: 0
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.468829, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1132.304077
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.122917, CIOU: -0.044101), Class: 0.570439, Obj: 0.484558, No Obj: 0.461125, .5R: 0.000000, .75R: 0.000000, count: 2
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.240738, CIOU: 0.204894), Class: 0.437907, Obj: 0.354213, No Obj: 0.513501, .5R: 0.000000, .75R: 0.000000, count: 3
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.467784, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1133.650391
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.255730, CIOU: 0.245869), Class: 0.405298, Obj: 0.524315, No Obj: 0.462522, .5R: 0.000000, .75R: 0.000000, count: 2
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.513409, .5R: -nan, .75R: -nan, count: 0
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.469859, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1134.588501
 train_network sum: 4529.271484 / 8
 8: 566.158936, 567.364441 avg, 0.000000 rate, 0.410363 seconds, 64 images
 Loaded: 0.000040 seconds
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.062998, CIOU: -0.028079), Class: 0.722950, Obj: 0.497665, No Obj: 0.463482, .5R: 0.000000, .75R: 0.000000, count: 4
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.511521, .5R: -nan, .75R: -nan, count: 0
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: -nan, CIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.467789, .5R: -nan, .75R: -nan, count: 0
 train_network_err: 1128.023071
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 82 Avg (IOU: 0.158216, CIOU: 0.137621), Class: 0.589739, Obj: 0.456860, No Obj: 0.465134, .5R: 0.000000, .75R: 0.000000, count: 3
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 94 Avg (IOU: 0.142218, CIOU: 0.011128), Class: 0.462262, Obj: 0.684095, No Obj: 0.513644, .5R: 0.000000, .75R: 0.000000, count: 2
 v3 (ciou loss, Normalizer: (iou: 0.500000, cls: 1.000000) Region 106 Avg (IOU: 0.190844, CIOU: 0.169876), Class: 0.442428, Obj: 0.458559, No Obj: 0.469251, .5R: 0.000000, .75R: 0.000000, count: 1
 train_network_err: 1140.072632
 
`
 
&mdash;

**Comment by 1343464520** [comment]
大佬。我在用你的repo编译时总是报错。。看了下跟opencv相关，应该是版本问题，我用的是3.4版本，不知道您的opencv用的哪个版本？

**Comment by Zzh-tju** [comment]
@1343464520 3.4.1
