### ISSUE TITLE
for k=161:180

### ISSUE THREAD

**Issue by henbucuoshanghai** [Zzh-tju/DIoU#7]
simple test为何分为三个阶段？梯度不是一样的？

**Comment by henbucuoshanghai** [comment]
matlab的代码实现的是 各种iou的bp梯度？公式就是paper里面的公式？然后求导？

**Comment by Zzh-tju** [comment]
分三个阶段是为了模拟训练时的学习率下降，我仿照训练VOC的方式，其学习率在4万，4.5万轮下降0.1 (最大5万轮)

是的，matlab实现的梯度与Darknet版本的YOLOv3一致。

**Comment by henbucuoshanghai** [comment]
paper里面的公式？求导？

**Comment by henbucuoshanghai** [comment]
a(k,1:4)=pred;
    loss=abs(a(k,1:4)-gt(1:4))+loss;
第一句：把每一次更新完的bbox坐标 均保存在a里面
第二句是什么意思呢？直接bbox的坐标和gt的四个欧氏距离 做差值？当做loss？

**Comment by henbucuoshanghai** [comment]
最后的plot画图画的是xywh？可查看迭代几次后的bbox位置？

**Comment by henbucuoshanghai** [comment]
希望解答 多谢  最后一个  梯度前面为什么2-IO    有学习率就可以  2-IO是哪来的？

**Comment by Zzh-tju** [comment]
具体细节都在论文
