### ISSUE TITLE
Radius = 3 for simulation

### ISSUE THREAD

**Issue by dikshaaswal** [Zzh-tju/DIoU#9]
As you have discussed in your paper Distance-IoU Loss: Faster and Better Learning for Bounding Box Regression, you have taken radius = 3, for simulation. Can you tell me reason behind taking it as 3. Is it practically possible, to consider larger N, like N=5 or 10 or 20?

**Comment by Zzh-tju** [comment]
Simulation experiment is just a simulation. If I took radius=2, you might ask me why did I take it 2. The experiment in the paper set 7×7×7×5000 regression cases. That is enough to see how these IoU-based losses work. You can try whatever you want, e.g., more regression cases or different radius.

**Comment by dikshaaswal** [comment]
I got your point . Thanks.
